"use client";

import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { GitMerge } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

function moneyValue(value) {
  const text = String(value || "").replace(/[$,\s]/g, "").toLowerCase();
  const numeric = Number.parseFloat(text);
  if (!Number.isFinite(numeric)) return 0;
  return text.includes("m") ? Math.round(numeric * 1_000_000) : text.includes("k") ? Math.round(numeric * 1_000) : Math.round(numeric);
}

export function CompareAlternativesModal({ open, onOpenChange, onSaveArtifact, canSaveArtifacts = true, busy = false }) {
  const [savingId, setSavingId] = useState(null);
  const alternatives = [
    {
      id: "a1",
      title: "Aggressive Renegotiation",
      desc: "Cancel unused licenses immediately and demand 15% discount on remaining commit.",
      savings: "$1.37M",
      cost: "$0",
      risk: "High",
      effort: "High",
      timeline: "2-4 weeks",
      confidence: "82%",
      recommended: true
    },
    {
      id: "a2",
      title: "Gradual Right-sizing",
      desc: "Phase out unused licenses over next 2 quarters, maintain current commit discount.",
      savings: "$850K",
      cost: "$0",
      risk: "Low",
      effort: "Low",
      timeline: "6 months",
      confidence: "95%",
      recommended: false
    },
    {
      id: "a3",
      title: "Switch to Competitor",
      desc: "Migrate BI workloads to AWS and use Google Workspace for office.",
      savings: "$2.1M",
      cost: "$450K",
      risk: "Critical",
      effort: "Critical",
      timeline: "12-18 months",
      confidence: "65%",
      recommended: false
    }
  ];
  const handleSelectOption = async (alternative) => {
    if (!canSaveArtifacts) {
      toast.error("Saving Workbench alternatives requires ask AI permission.");
      return;
    }
    if (!onSaveArtifact) {
      toast.error("Workbench artifact persistence is not connected.");
      return;
    }

    setSavingId(alternative.id);
    try {
      await onSaveArtifact({
        type: "alternative_analysis",
        title: alternative.title,
        content: alternative.desc,
        status: "saved",
        metrics: {
          expectedSavings: moneyValue(alternative.savings),
          riskExposure: alternative.risk === "Critical" ? 2_100_000 : alternative.risk === "High" ? 1_370_000 : 850_000,
          confidence: Number.parseInt(alternative.confidence, 10) || 0,
        },
        recommendations: alternatives.map((item) => ({
          id: item.id,
          title: item.title,
          detail: item.desc,
          impact: item.savings,
          selected: item.id === alternative.id,
        })),
        metadata: {
          selectedAlternativeId: alternative.id,
          risk: alternative.risk,
          effort: alternative.effort,
          timeline: alternative.timeline,
          implementationCost: alternative.cost,
        },
      });
      toast.success(`${alternative.title} saved to Workbench artifacts.`);
      onOpenChange(false);
    } catch (error) {
      toast.error(error.message || "Alternative could not be saved.");
    } finally {
      setSavingId(null);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[800px] bg-[#0E1116] border-[#28313C] text-white">
        <DialogHeader>
          <div className="flex items-center gap-3 mb-2">
            <div className="flex size-10 items-center justify-center rounded-lg border border-[#4EA1FF]/30 bg-[#4EA1FF]/10 text-[#4EA1FF]">
              <GitMerge className="size-5" />
            </div>
            <div>
              <DialogTitle>Compare Alternatives</DialogTitle>
              <DialogDescription className="text-muted-foreground text-xs mt-1">
                Evaluate strategic options generated by GENIUS for the Microsoft EA renewal.
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <div className="py-4 overflow-x-auto scrollbar-thin">
          <div className="grid grid-cols-4 gap-4 min-w-[700px]">
            {/* Header Column */}
            <div className="flex flex-col gap-4 mt-12 text-xs font-semibold uppercase tracking-widest text-muted-foreground text-right pr-4">
              <div className="h-10 flex items-center justify-end">Expected Savings</div>
              <div className="h-10 flex items-center justify-end">Implementation Cost</div>
              <div className="h-10 flex items-center justify-end">Risk Level</div>
              <div className="h-10 flex items-center justify-end">Effort Required</div>
              <div className="h-10 flex items-center justify-end">Timeline</div>
              <div className="h-10 flex items-center justify-end">AI Confidence</div>
            </div>

            {/* Data Columns */}
            {alternatives.map((alt) => (
              <div key={alt.id} className={`flex flex-col rounded-xl border ${alt.recommended ? 'border-primary bg-primary/5 shadow-[0_0_15px_rgba(78,161,255,0.1)]' : 'border-[#28313C] bg-[#141A22]'} overflow-hidden relative`}>
                {alt.recommended && (
                  <div className="absolute top-0 left-0 w-full bg-primary py-1 text-center text-[9px] font-bold uppercase tracking-widest text-primary-foreground">
                    Recommended
                  </div>
                )}
                <div className={`p-4 flex flex-col gap-1 border-b border-[#28313C] ${alt.recommended ? 'mt-4' : 'h-[88px] justify-center'}`}>
                  <span className="font-bold text-white text-sm leading-tight">{alt.title}</span>
                  <span className="text-[10px] text-muted-foreground leading-snug line-clamp-2" title={alt.desc}>{alt.desc}</span>
                </div>
                <div className="flex flex-col gap-4 p-4 text-sm font-medium text-white text-center">
                  <div className="h-10 flex items-center justify-center text-evidence font-bold">{alt.savings}</div>
                  <div className="h-10 flex items-center justify-center">{alt.cost}</div>
                  <div className="h-10 flex items-center justify-center">
                    <span className={`px-2 py-1 rounded text-xs font-bold ${
                      alt.risk === 'Low' ? 'bg-evidence/10 text-evidence' : 
                      alt.risk === 'High' ? 'bg-warning/10 text-warning' : 
                      'bg-critical/10 text-critical'
                    }`}>{alt.risk}</span>
                  </div>
                  <div className="h-10 flex items-center justify-center text-xs">{alt.effort}</div>
                  <div className="h-10 flex items-center justify-center text-xs">{alt.timeline}</div>
                  <div className="h-10 flex items-center justify-center text-xs text-primary">{alt.confidence}</div>
                </div>
                <div className="p-4 border-t border-[#28313C] mt-auto">
                  <Button type="button" onClick={() => handleSelectOption(alt)} disabled={Boolean(savingId) || busy} className={`w-full text-xs ${alt.recommended ? 'bg-primary text-primary-foreground hover:bg-primary/90' : 'bg-[#28313C] text-white hover:bg-[#28313C]'}`}>
                    {savingId === alt.id ? "Saving..." : "Select Option"}
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </div>

        <DialogFooter className="border-t border-[#28313C] pt-4 mt-2">
          <Button variant="ghost" className="text-muted-foreground hover:text-white text-xs" onClick={() => onOpenChange(false)}>
            Close Comparison
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
